Adds and adjusts information files
HybrisMC/.github pull request #1
Opened 2023-08-24 17:57 UTC by ethan-davies

## Summary
This Pull Request adds informative files to the respiratory the changes are as followed

- Created a `CODE_OF_CONDUCT.md`
- Created a `SECURITY.md` based of confirmed website features
- Created a `CONTRIBUTING.md`
- Updated the organisation `README.md` to link some of these information files

## Useful information
By adding these files to the `.github` repository will not mean it will get copied to the other repository’s source instead, with the `SECURITY.md` and `CODE_OF_CONDUCT.md` will get placed in a tab of there respective sections. **In short,** this means we would need a separate PR to add the files the the repository’s source to make it easily accessible to the visitor.

<sub>My bad for the unnecessary commits I’m currently on holiday and had to do it on mobile</sub>

2023-08-28 19:50 UTC, 770grappenmaker requested changes
The rest LGTM

2023-08-28 19:50 UTC, 770grappenmaker commented on profile/README.md
> +- Follow us on Twitter: [@COMING-SOON](https://x.com/)
This should not be there, we will not make a Twitter/X account.

2023-08-28 19:50 UTC, 770grappenmaker commented on profile/README.md
> +Hybris is mostly licensed under the [GNU General Public License v3.0](../LICENSE).
"Most of the projects maintained by Hybris" is probably better

2023-08-28 20:02 UTC, ethan-davies commented
I have just resolved the requested changes.

2023-08-28 20:28 UTC, 770grappenmaker approved these changes
Will await @RichardDorian for review.

2023-08-30 19:33 UTC, RichardDorian commented
Looks good to me too!

2023-08-30 19:34 UTC, RichardDorian approved these changes
Looks good to me too!

2023-08-30 19:35 UTC, merged